[tool.poetry]
name = "ofx-converter"
version = "0.1.0"
description = ""
authors = ["Lucas Marcondes <lucasnascimento95@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jinja2 = "^3.1.4"
debugpy = {version = "^1.8.6", optional = true}

[tool.poetry.extras]
dev = [
  "debugpy"
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
