default:
  converter:
    accounts:
      xpi-investimentos:
        files:
          format: csv
          in: ../statements/personal/xpi/investimentos/csv
          out: ../statements/personal/xpi/investimentos/ofx
        lang: por
        cur: brl
        fi:
          id: 102
          org: SC XP Investimentos
        account:
          branch: 0001
          id: 2187146
          type: checking
      xpi-conta:
        files:
          format: csv
          in: ../statements/personal/xpi/conta/csv
          out: ../statements/personal/xpi/conta/ofx
        lang: por
        cur: brl
        fi:
          id: 348
          org: Banco XP S.A.
        account:
          branch: 0001
          id: 2187146
          type: checking
