name: Pre-commit

on:
  pull_request:
    paths:
      - 'ofx_converter/**'
      - 'tests/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run Pre-Commit

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.6

    - name: Run Pre-commit
      uses: pre-commit/action@v3.0.1
