name: Test Python Package

on:
  pull_request:
    # branches:
    #   - develop
    #   - main
    paths:
      - 'ofx_converter/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.5

    - name: Install Dependencies
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest -v
